default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
  

development:
  <<: *default
  password: 
  database: katarine_development
  host: localhost
  username: shenze

test:
  <<: *default
  password:
  host: localhost
  database: katarine_test
  host: localhost
  username: shenze

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>